### ISSUE TITLE
Change Copy of Silk Yoga

### ISSUE THREAD

**Issue by Aiko-Kawamura** [NoteHive/Silk-Corp-Guide#24]
Write a definition discussing about Silk Yoga. Also follow the character count.

![image](https://user-images.githubusercontent.com/119849081/230444805-a5e637cd-bd11-44f6-a8d1-b18f16cee342.png)

* The definition may benefit from further elaboration on the specific techniques and goals of yoga practices, as well as the cultural and historical context in which yoga originated. Therefore, it is recommended that the definition of Yoga be reviewed and revised to ensure accuracy and comprehensiveness. 
* The idea of Silk Yoga is not just all about doing the poses but also overall health and wellness of the mind, body, and spirit.

https://silkcorp.org/

**Comment by Aiko-Kawamura** [comment]
I am working on this. 
https://github.com/Aiko-Kawamura/Silk-Corp-Guide/commit/f6c038f625318ccc63ba966dc876baa4b49ef817

**Comment by Remy-Reveltek** [comment]
@Aini-Bashir, let's work on it.
