### ISSUE TITLE
Change Copy of Silk Arts

### ISSUE THREAD

**Issue by Aiko-Kawamura** [NoteHive/Silk-Corp-Guide#26]
Clarify definition of Silk Arts. Also follow the character count.

![image](https://user-images.githubusercontent.com/119849081/230461942-913d47c8-8628-4ff0-a2e2-2687d732847a.png)

Description: The current definition of Silk Arts provided states that it is a wide range of human practices of creative expression, storytelling, and cultural participation that encompass multiple diverse and plural modes of thinking, doing, and being. However, this definition may be overly broad and lack specificity in terms of the types of creative expressions and cultural practices that are considered Silk Arts. Additionally, the definition may benefit from further elaboration on the historical and cultural contexts in which Silk Arts originated, as well as their significance and impact on society. Therefore, it is recommended that the definition of Silk Arts be reviewed and revised to ensure accuracy and comprehensiveness.

![image](https://user-images.githubusercontent.com/119849081/230476213-bf514fac-c241-4ae4-8f6f-e84b37b038b4.png)

[silkarts.org](https://silkcorp.org/)

**Comment by Aiko-Kawamura** [comment]
I am working on this issue. 
https://github.com/Aiko-Kawamura/Silk-Corp-Guide/commit/a5db32738e2bf5ffdc29838574a41260eedf69ab

**Comment by N-eng66** [comment]
I am going to make changes in this issue #26. There were some mistakes like "They" and "There" used instead of "We" and "Our".I am going to fix these mistakes now.
