### ISSUE TITLE
Change Copy of Silk Cafe

### ISSUE THREAD

**Issue by Aiko-Kawamura** [NoteHive/Silk-Corp-Guide#27]
Clarify definition of Silk Cafe. Also follow the character count.

![image](https://user-images.githubusercontent.com/119849081/230479606-7d1d6e00-6c39-492f-a383-4b7b7bc4b5a1.png)

Silk Cafe should consider expanding their menu to include more options for customers with dietary restrictions, such as gluten-free or vegan options. They should also review the quality of their baked goods and ice creams and ensure they are consistently up to their high standards. Offering new and innovative menu items could attract new customers and retain existing ones. Additionally, the cafe should focus on creating a comfortable and welcoming atmosphere to encourage repeat visits. 

Visit Silk Corp website for reference
https://silkcorp.org/

**Comment by Aiko-Kawamura** [comment]
I submitted PR for this issue.

**Comment by Remy-Reveltek** [comment]
@Aini-Bashir, let's work on it

**Comment by Aini-Bashir** [comment]
Please add a special "e" character in the alphabet of Cafe.

**Comment by Aini-Bashir** [comment]
Change the word "their" or "they" in the content of SILK Cafe.
