### ISSUE TITLE
Update content of "Silk Advantages"

### ISSUE THREAD

**Issue by Aiko-Kawamura** [NoteHive/Silk-Corp-Guide#35]
Write definition of Silk Advantages. Also follow the character count. 

![image](https://user-images.githubusercontent.com/119849081/230893537-b3a97ba1-2aeb-4af8-abd9-7dd617133fbc.png)

Issue Description: SILK Corp's unique mission and values provide several advantages to franchisees who choose to join the organization. These advantages include a positive brand reputation, a strong and diverse customer base, a commitment to social responsibility, and a focus on holistic well-being. By aligning their business operations with SILK Corp's mission and values, franchisees can leverage these advantages to enhance their own brand image, attract and retain customers, and promote sustainable and socially responsible practices.

Visit Silk Corp website for reference
[silkcorp.org](https://silkcorp.org/)

![image](https://user-images.githubusercontent.com/119849081/230897754-dc12bb19-7698-4a01-a13e-744514e2dca6.png)

**Comment by Remy-Reveltek** [comment]
@N-eng66, let's work on it.

**Comment by N-eng66** [comment]
I am working on this issue.

**Comment by N-eng66** [comment]
Read the issue description and brainstorm about the issue.

**Comment by N-eng66** [comment]
I have collected the data and researched the above issue and now I will implement it.
