### ISSUE TITLE
Update "Outreach Program" section

### ISSUE THREAD

**Issue by Aiko-Kawamura** [NoteHive/Silk-Corp-Guide#37]
Research and write content for "Outreach Program" of Silk Corp. that can be used for the franchise guide. 
Follow the character count.

![image](https://user-images.githubusercontent.com/119849081/230902421-41ea75c3-ea7c-45e8-a5db-ad504850ccba.png)

An outreach program is a type of initiative or project that is designed to reach out to a specific group of people or community, with the aim of providing support, education, or assistance. Outreach programs can take many different forms, depending on the specific goals and needs of the target audience.
The main goal of an outreach program is to build bridges between different groups in society and provide support or assistance where it is needed most. This can involve reaching out to marginalized or underserved communities, or it might involve working with individuals or groups who are experiencing a particular issue or challenge.

Visit Silk Corp website for reference. 
[silkcorp.org](https://silkcorp.org/)

**Comment by Aiko-Kawamura** [comment]
Reference link https://guide.silkcorp.org/

**Comment by Remy-Reveltek** [comment]
@Aini-Bashir, let's work on it

**Comment by SuzyQuant** [comment]
Edit these steps:

<img width="64" alt="image" src="https://github.com/NoteHive/Silk-Corp-Guide/assets/61100293/ba2e7674-da55-4e32-9021-02c5a9277d8c">


Editing it may change the character count.

**Comment by SuzyQuant** [comment]
<img width="350" alt="image" src="https://github.com/NoteHive/Silk-Corp-Guide/assets/61100293/d0dad0f1-c528-49e0-960b-d1f3dd313a59">

There are 3 lines. Make it two lines only.
