### ISSUE TITLE
Update "20 Years of Service" section

### ISSUE THREAD

**Issue by Aiko-Kawamura** [NoteHive/Silk-Corp-Guide#39]
Make a research about the "20 Years of Service" of Silk Corp.
Write a content that follows the character count in Silk Corp Franchise Guide. https://guide.silkcorp.org/

see image below
![image](https://user-images.githubusercontent.com/119849081/230955755-b3fc4723-c34c-48c2-ab69-1a5b3d274a1b.png)

Visit Silk Corp website for reference.
[silkcorp.org
](https://silkcorp.org/)

**Comment by Aini-Bashir** [comment]
I'm going to work on this issue.

**Comment by Aini-Bashir** [comment]
I did a PR on this issue.

**Comment by Remy-Reveltek** [comment]
@Aini-Bashir, let's work on it

**Comment by SuzyQuant** [comment]
Change and then check character count:

<img width="75" alt="image" src="https://github.com/NoteHive/Silk-Corp-Guide/assets/61100293/feb0c334-553e-4b9d-b1fa-8a33d0eff815">

**Comment by Aini-Bashir** [comment]
I will do my proper research, take help from the [Jorrney Business plan](https://www.joorney.com/samples/), and create a pull request on it as changes were requested.
