### ISSUE TITLE
Research on SILK Terminology

### ISSUE THREAD

**Issue by SuzyQuant** [NoteHive/Silk-Corp-Guide#396]
#### Overview/Background
The SILK LIFE program, with its foundational pillars of Strength, Integrity, Love, and Knowledge (S.I.L.K.), draws inspiration from the art of silk weaving to represent the interlacing of diverse life aspects into a resilient and adaptable lifestyle. To deepen our team's understanding and appreciation of this metaphorical framework—and to enhance the cultural exchange aspect of our program—we need comprehensive research on terms related to weaving, tapestry, looms, silk production, etc. This knowledge will not only enrich our internal lexicon but also enable us to craft content that resonates more deeply with these themes.

#### Tasks
- **Compilation Task**: Compile an extensive list of terms associated with weaving and tapestry-making. Provide a link to the research file.
- **Definition Task**: Provide clear definitions for each term in context with how they relate to both their traditional meanings and metaphorical applications within our program.
- **Cultural Significance Task**: Investigate the cultural significance behind various weaving techniques and patterns across different cultures.
- **Integration Strategy Task**: Develop strategies for integrating this terminology into SILK LIFE’s materials in a way that enhances the cultural exchange elements without overwhelming participants.

#### Acceptance Criteria
1. **Comprehensiveness**: The research should cover a broad range of relevant terms from basic concepts to more advanced techniques in weaving.
2. **Accuracy & Clarity**: All definitions must be accurate according to textile industry standards while being communicated clearly enough for layperson understanding.
3. **Cultural Depth**: Information provided should reflect the depth of cultural traditions associated with each term or concept researched.
4. **Relevance & Application:** Terms must be applicable within the context of SILK LIFE's mission statement; suggestions on application should align with Y.A.C.H.T pillars where possible.
5. **Inclusivity & Respectfulness:** Content must respect all cultures represented; it should educate without appropriating or misrepresenting any group’s heritage or practices.

By conducting thorough research on these topics, we aim not just at expanding our vocabulary but at fostering a deeper connection between our staff members’ work and the rich historical contexts that inform it—thus enhancing overall engagement in SILK LIFE’s Cultural Exchange Program initiatives.

LINKS:
https://github.com/NoteHive/Silk-Corp-Guide/blob/gh-pages/research/SILK%20Initial%20Illustrations.pdf

**Comment by SuzyQuant** [comment]
Here's my research notes for today:

https://github.com/NoteHive/Silk-Corp-Guide/edit/gh-pages/research/SQ%20Notes/01-04-2024.md

**Comment by Sana-Ramzan** [comment]
Today I   will collaborate with my team on issue #396 and I will research the terminology of SILK. I will also comment my smart in and research link on the issue#396.

**Comment by Sana-Ramzan** [comment]
My today's research notes.  
https://github.com/Sana-Ramzan/Silk-Corp-Guide/pull/2/commits/2098752d6cbb9d805167a465a20f640981bc52b1

**Comment by Sana-Ramzan** [comment]
Today I will continue my work on issue#396. and I will research about the terminology of   SILK. I will also continue my product management training with design hive team.

**Comment by Sana-Ramzan** [comment]
Today I will collaborate with my team on issue#396.I will also continue my product management training with design hive team. I will spend some time on Atlassian and learn more about Jira.

**Comment by Sana-Ramzan** [comment]
My research  notes                                                                     
 https://github.com/Sana-Ramzan/Silk-Corp-Guide/blob/fb8d938dea39bd0eb41fecabdec19e335dc6644d/notes/SILK%20Terminology.md

**Comment by Sana-Ramzan** [comment]
Today I will collaborate with my team on issue#396. I will also continue product management training with design hive team. I will also continue my Jira training on Atlassian.

**Comment by Sana-Ramzan** [comment]
Today I will work on issue #396. I will research how tapestry is different from other textile Arts. I will also discuss my research with my teammates.

**Comment by SuzyQuant** [comment]
https://github.com/NoteHive/Silk-Corp-Guide/edit/gh-pages/research/SQ%20Notes/01-04-2024.md

I'll be working on this issue and learning SILK Terminologies to help us in writing our Cultural Exchange Program. I'll put my 2 hours into this learning concept and then 2 hours to the TOC and check and update for changes. My other 2 hours will be on USIVA.

**Comment by Sana-Ramzan** [comment]
my todays research 
https://github.com/Sana-Ramzan/Silk-Corp-Guide/pull/2/files#diff-6908645bbd7cbc60d9a1109b9d6b36d4226880e675a1dbd5dd19260a199fd607

**Comment by Sana-Ramzan** [comment]
Today I will work on issue#396.I will research the terminologies of SILK.I will also watch videos about this.

**Comment by SuzyQuant** [comment]
Today, during my 4-hour Focus Shift, I intend to concentrate on Designing (D) within the Organize (O) stage by deepening the connection between the key terms derived from silk and wool content and enhancing our Table of Contents to better incorporate SILK philosophy. By the completion of my shift, the Table of Contents will have been expanded with relevant terms in a contextually rich manner that aligns with our project's cultural exchange goals.

For the remaining 2 hours, I'll collaborate with fellow team members in a meeting to refine the onboarding flow and I'll work on I-485 documentation processes.

**Comment by Sana-Ramzan** [comment]
updated research notes 
https://github.com/Sana-Ramzan/Silk-Corp-Guide/pull/2/commits/9b899c27ae4607fb8a2a3e7d7dea07ca095be632

**Comment by Sana-Ramzan** [comment]
Today I will collaborate with my team on this issue and learn more about the terminologies of SILK. I will also continue my product management training with design hive team.

**Comment by Aini-Bashir** [comment]
Today I will work on this issue. First, I'll read the whole description of the issue and understand the requirements and purpose of the issue. Then, I'll research the SILK Terminologies and create a pull request. I w ill spend only 2 hours on it to get literacy on the SILK concept.

**Comment by SuzyQuant** [comment]
In the next 4 hours, my Focus Shift will be to Design (D) and integrate weaving and tapestry terminology into our SILK LIFE materials. I aim to enhance cultural exchange and understanding by crafting clear metaphors that resonate with our S.I.L.K. philosophy that is reflected in the Table of Contents (TOC), enriching our content with terms that demonstrate our program's depth and application. By the end of my shift, I expect to have a revised TOC in our materials, ensuring they support the Strength, Integrity, Love, and Knowledge pillars without overwhelming our audience.

**Comment by SuzyQuant** [comment]
Yesterday, I wasn't able to work on the TOC because I was working on network system research and WE project.

Today's Focus Shift will be centering on Design (D) in our TOC, where I'll incorporate the list of weaving and tapestry-making terms I have researched into the TOC. The goal is to enhance the terminology and cultural appreciation within the SILK LIFE program, ensuring the inclusion of diverse weaving techniques and patterns. By the end of this shift, the TOC will be enriched with these terms, deepening the cultural exchange aspect of the program.

**Comment by SuzyQuant** [comment]
Today, I'll work on the SILK TOC that I have recently updated last Wednesday. With a set of fresh eyes, I need to see if the words that we're not supposed to be included are in the TOC, and check if everything flows well according to how SILK are made. I'll give updates to teammates on my notes.

https://github.com/NoteHive/Silk-Corp-Guide/tree/gh-pages/research/SQ%20Notes

**Comment by SuzyQuant** [comment]
Today, I'll work on the Design Development of the SILK TOC. Instead of focusing on text-heavy updates, I will give updates with drawings instead and often to the chat.

**Comment by SuzyQuant** [comment]
Today, I'll be working on the illustration of SILK Life Journey, I should be able to draw at least 2 illustrations of how the silkworms evolve in this 4-hour shift. The other 2 hours will be spent on team meetings and shadowing.

**Comment by Sana-Ramzan** [comment]
Today I will continue working on the issue#396. I will work  on the pictorial representation of Silkworm to SILK process. At the end of day I will share my work with teammates.
