### ISSUE TITLE
Update "Competition" under Analysis section

### ISSUE THREAD

**Issue by Aiko-Kawamura** [NoteHive/Silk-Corp-Guide#53]
Make research and write content for the "Competition" article. 
Follow the character count.

![image](https://user-images.githubusercontent.com/119849081/234372525-c5ab7971-e6ee-4769-9d7d-ae09b05368ee.png)

Issue description: 
Competition analysis is the process of identifying and evaluating the strengths and weaknesses of your competitors in the marketplace. It involves gathering and analyzing information about your competitors' products, marketing strategies, target audience, pricing, and other factors that may impact your business. 

The outcome of the competition analysis should be a detailed report that provides insights and recommendations for improving our competitive position in the market. We should also consider conducting regular updates to ensure that we stay up-to-date with changes in the market and our competitors' strategies.

Reference Links:
https://silkcorp.org/
https://guide.silkcorp.org/
https://www.joorney.com/samples/

**Comment by Remy-Reveltek** [comment]
@N-eng66, let's work on it.

**Comment by SuzyQuant** [comment]
https://www.joorney.com/samples/e2-business-plan-sample-hospitality-business/
<img width="537" alt="image" src="https://github.com/NoteHive/Silk-Corp-Guide/assets/61100293/756d6a26-13f3-468b-b1ff-d91d875d9145">


Create something similar.
