### ISSUE TITLE
Update Dummy Text of "Costa Rica"

### ISSUE THREAD

**Issue by Ahmedabhc** [NoteHive/Silk-Corp-Guide#68]
Update the dummy content of the **"Costa Rica"** section displayed in the picture. Ensure that the content follows the specified character counts and aligns with the values and objectives of SILK Corp.
![costa](https://github.com/NoteHive/Silk-Corp-Guide/assets/133792151/ecefa028-50d1-4165-96c4-44e80b10aa4d)

We need to improve this issue by describing, that we also give services in Costa Rica (To study about services read guide first paragraphs), and we are open to run our franchises in this regime of Central America too.

Moreover, also include that we also have worked in Costa Rica specially empowering the women's, children's etc. with the help of different contributors.

Impact: We need to place an impact of diversification on the reader that we're in all around the world and if any one join us no matter where he/she is residing we're open to contribute.

Study the link before starting to work on it:
https://github.com/NoteHive/Silk-Corp-Guide#readme

**To contribute to the GitHub repository, please follow the steps below:**

1. Fork the repository
2. Go to the gh-pages branch
3. Look for an index.html file
4. Find the area where the content needs to update
5. Update the content and commit changes

### You can also visit SILK Corp's website and franchise guide for more information.

- Website: https://silkcorp.org/
- Franchise Guide: https://guide.silkcorp.org/

**Comment by Ahmedabhc** [comment]
@NF11234, updated please review it.

**Comment by Aini-Bashir** [comment]
I'm going to work on this issue, will do proper research, and then do a PR on it.
