### ISSUE TITLE
Update the Content of "Lorem the It is a long established" above WHY SILK

### ISSUE THREAD

**Issue by Ahmedabhc** [NoteHive/Silk-Corp-Guide#82]
Update the dummy content of the **"Lorem the It is a long established"** section displayed in the picture. Ensure that the content follows the specified character counts and aligns with the values and objectives of SILK Corp.
![pic12](https://github.com/NoteHive/Silk-Corp-Guide/assets/133792151/3c387c37-b930-4245-8ace-2ffdb87f6c3d)

Work Ethic:
-Reliable
-Dedication
-Discipline
-Quality

Work Life Balance:
-Teaches how to balance between work and life,
-how to stay motivated,
-how to save energy after work to enjoy with family and friends.

Professionalism:
-The Silk corp team is truly amazing!
-Their creative
-Thinking and collaboration skills are unmatched
-SkyRocked our business with dedicated time.

Discuss all these points in detail, and also pitch readers that we're highly professional company and work on ethics and full our promises.
### If you are a new contributor study the link before starting to work on it:
https://github.com/NoteHive/Silk-Corp-Guide#readme

**To contribute to the GitHub repository, please follow the steps below:**

1. Fork the repository
2. Go to the gh-pages branch
3. Look for an index.html file
4. Find the area where the content needs to update by pressing ctrl+F
5. Go to the exact highlighted issue and make sure you don't change any list accidentally.
6. Do not change any code, just work inside glyphs 
7. FOR EXAMPLE: OUT OF BOUND>  **YOU WORK HERE**  <OUT OF BOUND
8. Update the content and commit changes

### You can also visit SILK Corp's website and franchise guide for more information.

- Website: https://silkcorp.org/
- Franchise Guide: https://guide.silkcorp.org/

**Comment by Aini-Bashir** [comment]
I worked on this issue and here is my PR: [issue# 82](https://github.com/NoteHive/Silk-Corp-Guide/pull/129)
